backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'books'
    label: 'books'
    folder: 'content/books'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publication', widget: 'datetime' }
      - { label: 'Release Date', name: 'release', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'ISBN', name: 'isbn', widget: 'string' }
      - { label: 'Image (max 500kb - preferable .jpg - lowercase name - no spaces)', name: post_image, widget: image, required: true, media_library: [{config: [{max_file_size: 62500}]}] }
      - { label: 'Image (max 500kb - preferable .jpg - lowercase name - no spaces square)', name: square_image, widget: image, required: true, media_library: [{config: [{max_file_size: 62500}]}] }
      - { label: 'Tags (comma separeted, no hashtags, spaces allowed)', name: 'tags', widget: 'list' }
      - { label: 'Download link', name: 'download', widget: 'string' }
      - { label: 'Other language link', name: 'language_link', widget: 'string' }
      - { label: 'Genre', name: 'genre', widget: 'select', options: ["fiction", "short-stories", "novella", "poetry", "nonfiction", "essay", "manifesto", "autobiography"], multiple: true }
      - { label: 'Time period', name: 'time_period', widget: 'select', options: ['19th', '20th', 'victorian', 'early-modern', 'modernist', 'contemporary'], multiple: true }
      - { label: 'Theme', name: 'theme', widget: 'select', options: ["motherhood", "LGBTQ+", "politics" ,"religion", "sex-romance", "suspense-gothic", "race", "science-technology", "first-person-narrator", "banned-book", "mental-health"], multiple: true }
      - { label: 'Language', name: 'lang', widget: 'select', options: [en, es] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Foreword & Cover', name: 'foreword', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
