backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'books'
    label: 'books'
    folder: 'content/books'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publication', widget: 'datetime' }
      - { label: 'Release Date', name: 'release', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'ISBN', name: 'isbn', widget: 'string' }
      - { label: 'Image (max 500kb - preferable .jpg - lowercase name - no spaces)', name: post_image, widget: image, required: true, media_library: [{config: [{max_file_size: 62500}]}] }
      - { label: 'Tags (comma separeted, no hashtags, spaces allowed)', name: 'tags', widget: 'list' }
      - { label: 'Download link', name: 'download', widget: 'string' }
      - { label: 'Language', name: 'lang', widget: 'select', options: [en, es] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
